### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Bummibaer** [OpenEtherCATsociety/SOES#10]
Hi,

is there any documentation for installation?
Was especially is kern.h?

regards,
Steffen

**Comment by nakarlsson** [comment]
There is a tutorial: http://openethercatsociety.github.io/doc/soes/tutorial_8txt.html

kern.h, It is not a SOES file, kern.h is an implementation specific header file for the sample code running on rt.labs RTOS rt-kernel. It can be removed/replaced in your project.
