### ISSUE TITLE
SDO abort message is returned with wrong CoE message type

### ISSUE THREAD

**Issue by asodja2** [OpenEtherCATsociety/SOES#115]
The SDO abort message is returned with wrong CoE message type (should be `SDO Res (3)`):
![CoE message type](https://user-images.githubusercontent.com/104766497/166225272-ef706d17-eb54-4d64-a6ab-a514df899096.png)

**Comment by nakarlsson** [comment]
How did you notice it? Does CTT capture this issue?

**Comment by asodja2** [comment]
> How did you notice it? Does CTT capture this issue?

It was reported by the EtherCAT master. What is CTT?
