### ISSUE TITLE
Read out PDOs that are not directly adressed to the slave

### ISSUE THREAD

**Issue by MarcelloDavis** [OpenEtherCATsociety/SOES#118]
Hello,

I am asking myself if it is possible for the slave device to read out PDOs that are not directly adressed to it by the master device?
Since the EtherCAT frame is transferred through all devices and sent back to the master, I thought that it may be possible to access the data on the fly?
Or does one have to configure the slave device on the EtherCAT-master in order to be able to access any PDO?

Thanks in advance!

**Comment by nakarlsson** [comment]
The slave doesn't have access to the frame, it can only access the DPRAM. For logic LRW PDOs that access is programmed via the FMMU by the master and the FMMU is read-only from the PDI, so you can't set it up from the slave.

**Comment by nakarlsson** [comment]
@MarcelloDavis , can we close this issue?

**Comment by MarcelloDavis** [comment]
> @MarcelloDavis , can we close this issue?

Yes, and thank you very much for your help!

**Comment by nakarlsson** [comment]
we'll close this, reopen or write a new if further questions
