### ISSUE TITLE
How to send PDO from SOES to SOSM?

### ISSUE THREAD

**Issue by tuhai711** [OpenEtherCATsociety/SOES#132]
Hello,
I have a bropblem, about PDO, SOSM only send (ec_send_processdata) then received (ec_receive_processdata) message from slave. How to slave auto send PDO (input/oputput) to master?

**Comment by nakarlsson** [comment]
That is how EtherCAT works, all traffic is driven by the master.

**Comment by tuhai711** [comment]
Yes. Thank you very much,

**Comment by tuhai711** [comment]
That mean, Slave can not notify PDO to Master, that is right?

**Comment by nakarlsson** [comment]
Not without the Master sending a frame.

**Comment by tuhai711** [comment]
Yes, I see.  If Master not sending a frame, Slave can not notify PDO to Master. Thank you.

**Comment by nakarlsson** [comment]
Please close "Issues" when no more questions

**Comment by tuhai711** [comment]
Hello Again, Can Slave use  SDO notify to master?

**Comment by nakarlsson** [comment]
No, the same goes for SDO. The master initiate read/write of the SDO.

**Comment by tuhai711** [comment]
Do you have method for salve notify to master?

**Comment by tuhai711** [comment]
Hello agaim, Do you know any method for salve notify to master without a master's request?

**Comment by nakarlsson** [comment]
No, the slaves never send frames

**Comment by nakarlsson** [comment]
Closed due to inactivity
