### ISSUE TITLE
How to use SOES without emulated EEPROM

### ISSUE THREAD

**Issue by elsp1991** [OpenEtherCATsociety/SOES#145]
I recently started working in a new ethercat slave project and I am struggling to understand how to use the stack without emulated eeprom. Basically my ESC has its own eeprom and should be able to deal with it, so the library doesnt need anymore to implement the EEP_Write EEP_read function in HAL but I am not sure how to remove these functions.

My guess is that in the ecat_config struct I have to leave the .esc_hw_eep_handler function pointer to NULL and the ESC itself would take care to process the request. In that case is easy but how can I acess the EEPROM from the application now?

**Comment by ArthurKetels** [comment]
Your guess is right. Just NULL the .esc_hw_eep_handler. 

Depending on your ESC hardware there needs to be an EEP_read() and EEP_write() function implemented. Look in your ESC datasheet how to do that. 

But many slave applications do not need to bother about the EEPROM because the interface is mostly used by the master side.

**Comment by elsp1991** [comment]
I can confirm my that setting NULL with a compatible ethercat slave controller the stack works fine the ESC is taking care to serve the EEPROM requests from the master

**Comment by elsp1991** [comment]
I am still digging in the ESC protocol to see if the application can have an abstracted(emulated or not) access to eeprom through the standard ESC protocol

**Comment by andarm** [comment]
Hi @ArthurKetels, 
If want to read the default value from eeprom, how the know the relation of xml and eeprom?  
Seems it is hard code in source code. That is confuse me.  Why not read eeprom match with the code?
i.g. 
![image](https://user-images.githubusercontent.com/14047502/230418217-f49835c5-0020-49c9-ba24-a2936c4b2f75.png)
![image](https://user-images.githubusercontent.com/14047502/230418532-2d806abd-f39e-4ab7-a8dc-87f160361ee7.png)

**Comment by nakarlsson** [comment]
Why do you need to read the EEPROM? In the picture above you refer to the ObjectDictionary, you can read that via the Obj struct and the .value member.

**Comment by andarm** [comment]
Thanks for your responnse. 
If xml has changed, my code have to fixed again. If can xml mapping in EEPROM and read it as configure file that would convinence.  Yes, via Obj struct it is working. That seems xml work for Master only, as the slave xml just for reference.  That is my confuse.

**Comment by nakarlsson** [comment]
That is how EtherCAT works. The XML for master to support Offline configuration.  The OD and EEPROM for online configuration

The OD for the slave application.

In general the slave doesn’t make use of the EEPROM. Some data is used during startup to write specific ESC registers, that is handled by the ESC.

So, if the application change, you should do a firmware upgrade to reflect that change.

**Comment by nakarlsson** [comment]
For parameters in the OD you can mark them as Backup And/Or Setting to support handling of persistent data. The store to flash or similar is implemented by the slave application.

If you spend some time reading the EtherCAT standards I think you’ll find your answers.

**Comment by andarm** [comment]
Got it, thanks @nakarlsson .

**Comment by nakarlsson** [comment]
Om further questions open a new issue
