### ISSUE TITLE
SOES and SOEM test

### ISSUE THREAD

**Issue by shangarnithi** [OpenEtherCATsociety/SOES#47]
Hi , 
I have successfully  compiled and installed SOES and SOEM in two different system(ubuntu 16).
How to check SOES and SOEM ?

***********************************************************************************************************************
**Slave side**

term@terminal:~/Desktop/SOES-master/build/applications/linux_lan9252demo$ sudo ./demo 
Hello Main

**Master side**

shan@nithi: ~/SOEM-master/build/test/linux/simple_test$ sudo ./simple_test enp1s0
[sudo] password for shan: 
SOEM (Simple Open EtherCAT Master)
Simple test
Starting simple test
ec_init on enp1s0 succeeded.
No slaves found!
End simple test, close socket
End program
shan@nithi:~/SOEM-master/build/test/linux/simple_test$ 

***********************************************************************************************************************
please someone suggest me how to test this. both the system i have connected physically over Ethernet.

**Comment by nakarlsson** [comment]
How does the setup look like? Do you use LAN9252 over SPI on the slave side?

**Comment by shangarnithi** [comment]
NO I dont have LAN9252 over SPI, Just i have cross-cabled  it with LAN cable

**Comment by nakarlsson** [comment]
Ok, then you need to study how EtherCAT works and are intended to work, this is not the forumt for that

**Comment by shangarnithi** [comment]
Ok Thanks for the prompt response, Actually I want to simulate and understand about Ethercat . As of now i dont have any hardware related to it. 
Can you please tell me the procedure or share the documents links ? so that i can start my understanding immediately .

**Comment by nakarlsson** [comment]
Look aroud at https://www.ethercat.org/ .
