### ISSUE TITLE
DPRINT depends on rpint library that is not available for ARM cortex M4

### ISSUE THREAD

**Issue by elsp1991** [OpenEtherCATsociety/SOES#57]
As one of the supported hardware for SOES is the XMC microcontroller family from Infineon, I think make sense that the code should be able to compile for it as well. With the current implementation of the DPRINT is not possible as the rprint library is no available for cortex m4.

Do you think that including a rprint.h file in the xmc_hal folder that retarget the rprintp function to printf would be a nice solution.

**Comment by nakarlsson** [comment]
we'll look into it, at the moment you'll have to modify it to your platform
