### ISSUE TITLE
ZYNQ7000: FoE: missing last 3 byte in each packet

### ISSUE THREAD

**Issue by shinnoyishi** [OpenEtherCATsociety/SOES#78]
Hello,

I am running SOES on ZYNQ7000 board, 
It can enter operation mode and everything looks fine.
But when I try to test FoE function, I found that the last 3 byte in each packet is always missing. The rest are correct.
Any idea?
Thank you in advance.

**Comment by nakarlsson** [comment]
Please post a wireshark and perhaps a sample file that fails?

**Comment by shinnoyishi** [comment]
Hi nakarlsson,


Attached is the result of Wireshark.
I compared it also with Beckhoff SSC stack.
FoE_SSC is the one tested with SSC stack.
Check packet 307 the data is correct.
Read data from IP core is also correct.


FoE_SOES is the one tested with SOES stack.
Check packet 323 the data is also correct.


But If I try to read the data from IP core, it seems not correct from SOES stack



The last 3 byte is 0 0 0 while it should be ff ff ff.


Thank you!


And as a background:


We are using EtherCAT IP core from Beckhoff in FPGA side and stack on ARM side on ZYNQ 7020.
The IP core is verified with SSC stack.





At 2020-07-16 16:32:22, "nakarlsson" <notifications@github.com> wrote:

Please post a wireshark and perhaps a sample file that fails?

**Comment by nakarlsson** [comment]
I think you need to attach the files at the Github Issues, not via mail, I can't see them anyway. Can you share your sample application and configuration in some way? It's possible to send to support[at]rt-labs.com

Please clarify where this missing 3 bytes are detected, function and line in SOES. Just reading from IP is too vague. Does that mean in ESC_read/write or in Mailbox read/write or in FOE write or FOE read function.
"
But If I try to read the data from IP core, it seems not correct from SOES stack
The last 3 byte is 0 0 0 while it should be ff ff ff.
"

**Comment by nakarlsson** [comment]
can we close this? we've other customers using Zynq that don't experience this problem using FoE.

**Comment by shinnoyishi** [comment]
Hi,

Yes, please close it.
Thank you.
