### ISSUE TITLE
Please implement EoE

### ISSUE THREAD

**Issue by tacarrie** [OpenEtherCATsociety/SOES#8]
"Ethernet over EtherCAT" (EoE) seems not to be supported yet by SOES.
This is a pitty, as I would like to use EoE to connect from my Master EtherCAT PC to my EtherCAT Slave PC in order to establish for example a Telnet or FTP connection.

**Comment by mheden** [comment]
It's something we have on our wishlist as well but we don't have a release plan for it at the moment.

**Comment by nakarlsson** [comment]
done
