### ISSUE TITLE
SDO_findsubindex can be exported

### ISSUE THREAD

**Issue by VijnanBhairav** [OpenEtherCATsociety/SOES#85]
_SDO_findsubindex_ is useful function for a client to find object entries from object dictionary. In last commit it is made static, request to declare in _esc_coe.h_ .  Similarly _SDO_findobject_ is another function which is not declared in `esc.coe.h`

**Comment by nakarlsson** [comment]
have been addressed in https://github.com/OpenEtherCATsociety/SOES/pull/86

**Comment by VijnanBhairav** [comment]
Thanks for the update. I also mentioned `SDO_findobject` along with SDO_findsubindex in above request, will it be possible to consider that too.
